version: '3.9'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - python3 #gunicorn
      - manage.py #somesite.wsgi:application
      - runserver #--bind
      - 0.0.0.0:8080
    ports:
      - "8000:8080"
    restart: always
    env_file:
      - .env
    volumes:
      - ./somesite/database:/app/database
    # logging:
    #   driver: "json-file"
    #   options: 
    #     max-file: "10"
    #     max-size: "200k"

    logging:
      driver: loki
      options:
        # loki-url: http://localhost:3100/loki/api/v1/push
        loki-url: http://host.docker.internal:3100/loki/api/v1/push

  grafana:
    image: grafana/grafana:9.2.15
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=true
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"