# Generated by Django 4.2.3 on 2023-08-22 14:18

from django.db import migrations, models
import myauthapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauthapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='profiel_image',
            field=models.ImageField(null=True, upload_to=myauthapp.models.profiel_image_directory_path),
        ),
    ]
