# Generated by Django 4.2.3 on 2023-08-22 16:05

from django.db import migrations, models
import django.db.models.deletion
import myauthapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauthapp', '0002_profiel_profiel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiel',
            name='profiel_image',
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=myauthapp.models.profiel_image_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='myauthapp.profiel')),
            ],
        ),
    ]
