# Generated by Django 4.2.3 on 2023-08-22 16:56

from django.db import migrations, models
import myauthapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauthapp', '0003_remove_profiel_profiel_image_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=myauthapp.models.profiel_image_directory_path),
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
